#!/bin/bash
# /etc/kernel.d/pre-install/20-rm_grub
# (Optional) Part of Void-Kernel-Hooks, under GPL-3.0 license
# Remove 50-efibootmgr and 50-grub scripts if they exist.  We are using grub,
# but using links so that grub.cfg does not need updated with kernel changes
#
	rm -f /etc/kernel.d/post-install/50-efibootmgr
	rm -f /etc/kernel.d/post-install/50-grub
	rm -f /etc/kernel.d/post-remove/50-efibootmgr
	rm -f /etc/kernel.d/post-remove/50-grub
exit $?
