#!/bin/bash
#
# Kernel post-install hook to regenerate links to latest kernel.
# We are using links so that grub.cfg does not need updated with kernel changes

## Refresh links to newly installed kernel in /boot  
PKGNAME="$1"
VERSION="$2"
NEW_INITRAMFS="initramfs-${VERSION}.img"
NEW_VMLINUZ="vmlinuz-${VERSION}"

ln -sf /boot/${NEW_INITRAMFS} /boot/initramfs-linux.img
ln -sf /boot/${NEW_VMLINUZ} /boot/vmlinuz-linux
echo "Kernel booted by grub.cfg, <vmlinuz-linux> successfully relinked to "$NEW_VMLINUZ
exit $?
